In [1]:
import csv
import datetime
from operator import sub
import numpy as np
import pandas as pd

In [2]:
test = pd.read_csv("test_ver2.csv",dtype={"sexo":str,
                                                    "ind_nuevo":str,
                                                    "ult_fec_cli_1t":str,
                                                    "indext":str,
                                                    "conyuemp":str})

train = pd.read_csv("train_ver2.csv",dtype={"sexo":str,
                                                    "ind_nuevo":str,
                                                    "ult_fec_cli_1t":str,
                                                    "indext":str,
                                                    "conyuemp":str})

/Users/nickryan/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (5,8,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df = train.append(test)

In [4]:
from sys import getsizeof
getsizeof(df)

15897652226

In [15]:
df.loc[df['fecha_dato'] == "2015-07-28"]

,age,antiguedad,canal_entrada,cod_prov,conyuemp,fecha_alta,fecha_dato,ind_actividad_cliente,ind_ahor_fin_ult1,ind_aval_fin_ult1,...,indresi,ncodpers,nomprov,pais_residencia,renta,segmento,sexo,tipodom,tiprel_1mes,ult_fec_cli_1t
3776494,24,46,KHE,36.0,NaN,2011-09-30,2015-07-28,0.0,0.0,0.0,...,S,952006,PONTEVEDRA,ES,85873.6,03 - UNIVERSITARIO,V,1.0,I,NaN
3776495,39,106,KFC,30.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640574,MURCIA,ES,86777.6,01 - TOP,V,1.0,A,NaN
3776496,29,106,KFC,15.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640570,"CORUÃ‘A, A",ES,88217.9,03 - UNIVERSITARIO,H,1.0,A,NaN
3776497,61,106,KAJ,9.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640567,BURGOS,ES,43855.1,02 - PARTICULARES,V,1.0,I,NaN
3776498,65,106,KFC,18.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640565,GRANADA,ES,77415.1,02 - PARTICULARES,H,1.0,A,NaN
3776499,51,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640564,VALLADOLID,ES,51561.2,01 - TOP,H,1.0,A,NaN
3776500,40,106,KFC,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640563,MADRID,ES,78912.4,02 - PARTICULARES,V,1.0,I,NaN
3776501,37,98,KAT,21.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640562,HUELVA,ES,42791.8,02 - PARTICULARES,V,1.0,A,NaN
3776502,76,106,KAT,46.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640558,VALENCIA,ES,NaN,02 - PARTICULARES,H,1.0,I,NaN
3776503,40,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640556,VALLADOLID,ES,90429,02 - PARTICULARES,V,1.0,A,NaN
3776504,37,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640555,VALLADOLID,ES,112554,02 - PARTICULARES,H,1.0,I,NaN
3776505,30,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640553,VALLADOLID,ES,47215.1,02 - PARTICULARES,H,1.0,I,NaN
3776506,38,106,KFC,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640551,MADRID,ES,152644,02 - PARTICULARES,H,1.0,I,NaN
3776507,41,106,KFC,11.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640549,CADIZ,ES,116533,02 - PARTICULARES,V,1.0,I,NaN
3776508,40,106,KFC,50.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640548,ZARAGOZA,ES,108026,02 - PARTICULARES,H,1.0,I,NaN
3776509,39,106,KFC,8.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640545,BARCELONA,ES,52327.4,02 - PARTICULARES,H,1.0,I,NaN
3776510,38,106,KAT,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640541,MADRID,ES,NaN,02 - PARTICULARES,H,1.0,I,NaN
3776511,44,105,KAT,28.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640538,MADRID,ES,121765,02 - PARTICULARES,H,1.0,A,NaN
3776512,45,106,KAT,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640537,MADRID,ES,NaN,02 - PARTICULARES,V,1.0,I,NaN
3776513,65,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640536,VALLADOLID,ES,82189,02 - PARTICULARES,H,1.0,I,NaN
3776514,65,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640535,VALLADOLID,ES,NaN,02 - PARTICULARES,V,1.0,I,NaN
3776515,63,106,KFC,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640533,MADRID,ES,185670,02 - PARTICULARES,H,1.0,I,NaN
3776516,61,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640529,VALLADOLID,ES,74802.3,02 - PARTICULARES,H,1.0,A,NaN
3776517,41,106,KAJ,47.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640525,VALLADOLID,ES,58119.7,02 - PARTICULARES,V,1.0,I,NaN
3776518,43,54,KFC,28.0,NaN,2006-09-09,2015-07-28,1.0,0.0,0.0,...,S,640575,MADRID,ES,161960,02 - PARTICULARES,H,1.0,A,NaN
3776519,31,106,KAJ,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640582,MADRID,ES,53886,02 - PARTICULARES,V,1.0,I,NaN
3776520,60,106,KAJ,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640583,MADRID,ES,87219.9,02 - PARTICULARES,H,1.0,I,NaN
3776521,54,106,KBZ,28.0,NaN,2006-09-09,2015-07-28,0.0,0.0,0.0,...,S,640584,MADRID,ES,225725,02 - PARTICULARES,V,1.0,I,NaN
3776522,57,106,KAT,28.0,NaN,2006-09-10,2015-07-28,1.0,0.0,0.0,...,S,640624,MADRID,ES,160376,02 - PARTICULARES,H,1.0,A,NaN
3776523,37,106,KFC,28.0,NaN,2006-09-10,2015-07-28,0.0,0.0,0.0,...,S,640623,MADRID,ES,95659.1,02 - PARTICULARES,V,1.0,I,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4606281,20,0,NaN,28.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407944,MADRID,ES,138441,NaN,V,1.0,NaN,NaN
4606282,34,0,NaN,15.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407943,"CORUÃ‘A, A",ES,90971.9,NaN,H,1.0,NaN,NaN
4606283,20,0,NaN,36.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407942,PONTEVEDRA,ES,105910,NaN,V,1.0,NaN,NaN
4606284,19,0,NaN,36.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407940,PONTEVEDRA,ES,69535.2,NaN,H,1.0,NaN,NaN
4606285,20,0,NaN,15.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407962,"CORUÃ‘A, A",ES,148833,NaN,H,1.0,NaN,NaN
4606286,21,0,NaN,41.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407992,SEVILLA,ES,44269.6,NaN,H,1.0,NaN,NaN
4606287,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407963,BARCELONA,ES,71177.7,NaN,V,1.0,NaN,NaN
4606288,31,0,NaN,46.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407965,VALENCIA,ES,50978.3,NaN,H,1.0,NaN,NaN
4606289,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407990,BARCELONA,ES,45505.7,NaN,V,1.0,NaN,NaN
4606290,21,0,NaN,12.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407988,CASTELLON,ES,54147.2,NaN,V,1.0,NaN,NaN
4606291,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407987,BARCELONA,ES,100546,NaN,V,1.0,NaN,NaN
4606292,23,0,NaN,8.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407986,BARCELONA,ES,60508.2,NaN,H,1.0,NaN,NaN
4606293,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407985,BARCELONA,ES,75525.9,NaN,V,1.0,NaN,NaN
4606294,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407984,BARCELONA,ES,352154,NaN,V,1.0,NaN,NaN
4606295,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407983,BARCELONA,ES,NaN,NaN,H,1.0,NaN,NaN
4606296,20,0,NaN,7.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407982,"BALEARS, ILLES",ES,NaN,NaN,H,1.0,NaN,NaN
4606297,53,0,NaN,12.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407979,CASTELLON,ES,64143.9,NaN,H,1.0,NaN,NaN
4606298,39,0,NaN,28.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407978,MADRID,ES,120383,NaN,H,1.0,NaN,NaN
4606299,78,0,NaN,38.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407976,SANTA CRUZ DE TENERIFE,ES,109055,NaN,V,1.0,NaN,NaN
4606300,22,0,NaN,15.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407975,"CORUÃ‘A, A",ES,9781.2,NaN,H,1.0,NaN,NaN
4606301,62,0,NaN,46.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407973,VALENCIA,ES,141980,NaN,H,1.0,NaN,NaN
4606302,32,0,NaN,28.0,NaN,2015-07-17,2015-07-28,1.0,0.0,0.0,...,S,1407972,MADRID,ES,155303,NaN,H,1.0,NaN,NaN
4606303,26,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407971,BARCELONA,ES,87676.9,NaN,V,1.0,NaN,NaN
4606304,21,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407970,BARCELONA,ES,76866.9,NaN,V,1.0,NaN,NaN
4606305,34,0,NaN,1.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407969,ALAVA,ES,NaN,NaN,V,1.0,NaN,NaN
4606306,20,0,NaN,8.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407968,BARCELONA,ES,80915.5,NaN,V,1.0,NaN,NaN
4606307,21,0,NaN,36.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407967,PONTEVEDRA,ES,45612.9,NaN,H,1.0,NaN,NaN
4606308,23,0,NaN,36.0,NaN,2015-07-17,2015-07-28,0.0,0.0,0.0,...,S,1407964,PONTEVEDRA,ES,259835,NaN,V,1.0,NaN,NaN
4606309,26,46,KHE,15.0,NaN,2011-09-30,2015-07-28,1.0,0.0,0.0,...,S,952008,"CORUÃ‘A, A",ES,121573,03 - UNIVERSITARIO,V,1.0,A,NaN
4606310,66,16,KFC,39.0,NaN,2014-03-21,2015-07-28,1.0,0.0,0.0,...,S,1249760,CANTABRIA,ES,82992.5,02 - PARTICULARES,V,1.0,A,NaN

In [5]:
train_df, test_df = df[:3776494], df[3776494:]
del train
del test
del df

In [6]:
# V2 create n lag features for feature
def lag_features(df, feature, number_lags):
    for lag in xrange(1, number_lags + 1):
        df['lag_' + str(lag) + '_' + feature] = 0
    target = df.loc[df['ncodpers'] == cust][feature]
    for cust in list(set(df['ncodpers'])):
        for lag in xrange(1, number_lags + 1):
            df.loc[(df['ncodpers'] == cust), 'lag_' + str(lag) + '_' + feature] = target.shift(lag)

# create n lag features for feature
def lag_features(df, feature, number_lags):
    unique_customers = list(set(df['ncodpers']))
    for lag in xrange(1, number_lags + 1):
        df['lag_' + str(lag) + '_' + feature] = "Null"
    for cust in unique_customers:
        targ = df.loc[df['ncodpers'] == cust][feature]
        for lag in xrange(1, number_lags + 1):
            df.loc[(df['ncodpers'] == cust), 'lag_' + str(lag) + '_' + feature] = targ.shift(lag)

In [ ]:
featurelist = [ 'ind_empleado',
 'pais_residencia',
 'ind_nuevo',
 'indrel',
 'ult_fec_cli_1t',
 'indrel_1mes',
 'tiprel_1mes',
 'indresi',
 'indext',
 'conyuemp',
 'indfall',
 'tipodom',
 'cod_prov',
 'nomprov',
 'ind_actividad_cliente',
 'renta',
 'segmento',
 'ind_ahor_fin_ult1',
 'ind_aval_fin_ult1',
 'ind_cco_fin_ult1',
 'ind_cder_fin_ult1',
 'ind_cno_fin_ult1',
 'ind_ctju_fin_ult1',
 'ind_ctma_fin_ult1',
 'ind_ctop_fin_ult1',
 'ind_ctpp_fin_ult1',
 'ind_deco_fin_ult1',
 'ind_deme_fin_ult1',
 'ind_dela_fin_ult1',
 'ind_ecue_fin_ult1',
 'ind_fond_fin_ult1',
 'ind_hip_fin_ult1',
 'ind_plan_fin_ult1',
 'ind_pres_fin_ult1',
 'ind_reca_fin_ult1',
 'ind_tjcr_fin_ult1',
 'ind_valo_fin_ult1',
 'ind_viv_fin_ult1',
 'ind_nomina_ult1',
 'ind_nom_pens_ult1',
 'ind_recibo_ult1']


start_time = datetime.datetime.now()
print start_time

lag_features(train_df, 'ind_empleado', 5)   

print(datetime.datetime.now()-start_time)

2016-12-15 00:16:50.576131